name: Deploy prod settings

env:
  build_number_prefix: '1.0'

on:
  push:
#    tags: "service-*"
    branches: [ test ]
    paths:
    - 'Settings/**'
    
jobs:
  publish:
    name: deploy settings 
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@master
    - name: Build and publish Settings Server
      uses: dvyu/Publish-Docker-Github-Action@master
      with:
        name: swisschains/settings-sirius-prod
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: ./Settings
        build_number_prefix: ${{ env.build_number_prefix }}
        build_number: ${{ github.run_number }}
        #tag_names: true  
        #tag_name_skip: service-  
        # snapshot: true # use snapshot to push an additional image, which is tagged with {YEAR}{MONTH}{DAY}{HOUR}{MINUTE}{SECOND}{first 6 digits of the git sha}
    - name: Update Settings Server
      uses: swisschain/kube-replace-pods@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_TEST }}
        YAML_FILE: Pods/Sirius/Settings/deployment.yaml
        BUILD_NUMBER_PREFIX: ${{ env.build_number_prefix }}
        BUILD_NUMBER: ${{ github.run_number }}
